[package]
name = "compta"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui_extras = { version = "*", features = ["all_loaders"] }
egui-file-dialog = "0.9.0"
egui_commonmark = "0.20"
image = { version = "0.25", default-features = false, features = ["png"] }
